const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('nav button')],page=document.querySelector('#page');
function go(n){pages.forEach(x=>x.classList.toggle('active',+x.dataset.p===n));nav.forEach(x=>x.classList.toggle('active',+x.dataset.go===n));page.textContent=String(n).padStart(2,'0')+' / 06';pages[n-1].scrollTop=0}
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(+x.dataset.go));
const reveal=document.querySelector('#reveal'),details=document.querySelector('#details');
const translations={
te:{om:'ॐ శ్రీ గణేశాయ నమః',sloka:'వక్రతుండ మహాకాయ కోటి సూర్య సమప్రభ<br>నిర్విఘ్నం కురుమే దేవ శుభకార్యేషు సర్వదా',heroTitle:'సారే వారి<br><em>పెళ్లిసందడి</em>',heroSub:'A celebration of love, family & forever',open:'వివాహ ఆహ్వానాన్ని తెరవండి →',auspicious:'॥ శుభమస్తు ॥',twoFamilies:'రెండు మనసులు • రెండు కుటుంబాలు • ఒక అందమైన బంధం',names:'శ్రీకాంత్ <i>♥</i> నిహారిక',journey:'జీవితాంతం కలిసి నడిచే<br>అందమైన ప్రయాణానికి తొలి అడుగు',invite:'పెద్దల ఆశీస్సులతో మా వివాహ మహోత్సవానికి<br>మీరు కుటుంబ సమేతంగా విచ్చేసి వధూవరులను ఆశీర్వదించవలసిందిగా<br>మనస్ఫూర్తిగా ఆహ్వానిస్తున్నాము.',familyBtn:'కుటుంబ పరిచయం →',familyLabel:'॥ వధూవరుల కుటుంబ పరిచయం ॥',auspiciousTime:'శుభ మంగళ వేళ',groomLabel:'వరుడు ||',groom:'శ్రీకాంత్',brideLabel:'వధువు ||',bride:'నిహారిక',blessing:'“మంగళం భగవాన్ విష్ణుః • మంగళం గరుడధ్వజః”',groomFather:'సారే భాస్కర్ బాబు',groomMother:'శ్రీమతి నాగ లక్ష్మి',brideFather:'బలివాడ రమేష్',brideMother:'శ్రీమతి చంద్రమతి',muhurthamBtn:'శుభ ముహూర్తం →',muhurthamLabel:'॥ శుభ ముహూర్తం ॥',weddingHour:'కళ్యాణ ఘడియ',month:'OCTOBER',hint:'మంగళ ఘడియను దర్శించేందుకు క్రింద ఉన్న బటన్‌ను నొక్కండి',reveal:'✦ ముహూర్తం వెల్లడించండి ✦',timeLabel:'వివాహ సమయం',time:'రాత్రి 07:29',dateLine:'శుభ ముహూర్తం • గురువారం • 29 అక్టోబర్ 2026',days:'రోజులు',hours:'గంటలు',minutes:'నిమిషాలు',seconds:'సెకన్లు',weekday:'గురువారం • 2026',venueName:'టౌన్ హాల్',venueCity:'భీమవరం',venueBtn:'కళ్యాణ వేదిక →',venueLabel:'॥ కళ్యాణ వేదిక ॥',welcome:'మీ రాక కోసం ఎదురుచూస్తూ...',venueSmall:'కళ్యాణ వేదిక',maps:'📍 Google Mapsలో వేదికను చూడండి',venueMsg:'మీ అమూల్యమైన సమయాన్ని మాతో పంచుకుని<br>వధూవరులను ఆశీర్వదించండి.',finalBtn:'చివరి ఆహ్వానం →',save:'SAVE THE DATE',finalNames:'శ్రీకాంత్<br><i>♥</i><br>నిహారిక',quote:'“ఇద్దరి కలయికతో మొదలయ్యే ఈ కొత్త జీవిత ప్రయాణం<br>సంతోషాలతో, ప్రేమతో, మంగళాలతో నిండాలని కోరుకుంటూ...”',blessings:'మీ ఆశీస్సులే మా తొలి కానుక',again:'ఆహ్వాన పత్రికను మళ్లీ చూడండి ↺',revealDone:'♥ మంగళ ముహూర్తం ♥',hintDone:'శుభ ముహూర్తం ఇదిగో మీ ముందుంది ✨',musicOn:'Music ON',musicOff:'Music OFF'},
en:{om:'Om Shri Ganeshaya Namah',sloka:'Vakratunda Mahakaya Koti Surya Samaprabha<br>Nirvighnam Kurume Deva Shubha Karyeshu Sarvada',heroTitle:'Sare Family<br><em>Wedding Celebration</em>',heroSub:'A celebration of love, family & forever',open:'Open Wedding Invitation →',auspicious:'॥ Auspicious Beginnings ॥',twoFamilies:'Two hearts • Two families • One beautiful bond',names:'Srikanth <i>♥</i> Niharika',journey:'The first step into a beautiful journey<br>of walking together for a lifetime',invite:'With the blessings of our elders, we cordially invite you<br>and your family to grace our wedding celebration<br>and bless the bride and groom.',familyBtn:'Meet the Families →',familyLabel:'॥ Introducing the Bride & Groom Families ॥',auspiciousTime:'A Blessed Beginning',groomLabel:'GROOM ||',groom:'Srikanth',brideLabel:'BRIDE ||',bride:'Niharika',blessing:'“May this union be blessed with auspiciousness, love and prosperity.”',groomFather:'Sare Bhaskar Babu',groomMother:'Smt. Naga Lakshmi',brideFather:'Balivada Ramesh',brideMother:'Smt. Chandramathi',muhurthamBtn:'Wedding Muhurtham →',muhurthamLabel:'॥ Auspicious Muhurtham ॥',weddingHour:'The Wedding Hour',month:'OCTOBER',hint:'Press the button below to reveal the auspicious wedding time',reveal:'✦ Reveal Muhurtham ✦',timeLabel:'WEDDING TIME',time:'7:29 PM',dateLine:'Auspicious Muhurtham • Thursday • 29 October 2026',days:'DAYS',hours:'HOURS',minutes:'MINUTES',seconds:'SECONDS',weekday:'THURSDAY • 2026',venueName:'Town Hall',venueCity:'Bhimavaram',venueBtn:'Wedding Venue →',venueLabel:'॥ Wedding Venue ॥',welcome:'Awaiting Your Presence...',venueSmall:'WEDDING VENUE',maps:'📍 View Venue on Google Maps',venueMsg:'Share your precious time with us<br>and bless the bride and groom.',finalBtn:'Final Invitation →',save:'SAVE THE DATE',finalNames:'Srikanth<br><i>♥</i><br>Niharika',quote:'“May this new journey that begins with their union<br>be filled with happiness, love and countless blessings...”',blessings:'Your blessings are our first gift',again:'View Invitation Again ↺',revealDone:'♥ Auspicious Muhurat ♥',hintDone:'The auspicious wedding time is revealed ✨',musicOn:'Music ON',musicOff:'Music OFF'},
hi:{om:'ॐ श्री गणेशाय नमः',sloka:'वक्रतुण्ड महाकाय कोटि सूर्य समप्रभ<br>निर्विघ्नं कुरु मे देव शुभ कार्येषु सर्वदा',heroTitle:'सारे परिवार की<br><em>शुभ विवाह बेला</em>',heroSub:'प्रेम, परिवार और जीवनभर साथ का उत्सव',open:'विवाह निमंत्रण खोलें →',auspicious:'॥ शुभारंभ ॥',twoFamilies:'दो दिल • दो परिवार • एक सुंदर बंधन',names:'श्रीकांत <i>♥</i> निहारिका',journey:'जीवनभर साथ चलने वाली<br>एक सुंदर यात्रा की पहली शुरुआत',invite:'बड़ों के आशीर्वाद से हम अपने विवाह समारोह में<br>आपको सपरिवार आमंत्रित करते हैं। कृपया पधारकर<br>वर-वधू को अपना आशीर्वाद प्रदान करें।',familyBtn:'परिवार से परिचय →',familyLabel:'॥ वर-वधू के परिवार का परिचय ॥',auspiciousTime:'शुभ मंगल बेला',groomLabel:'वर ||',groom:'श्रीकांत',brideLabel:'वधू ||',bride:'निहारिका',blessing:'“मंगलं भगवान विष्णुः • मंगलं गरुड़ध्वजः”',groomFather:'सारे भास्कर बाबू',groomMother:'श्रीमती नाग लक्ष्मी',brideFather:'बलिवाडा रमेश',brideMother:'श्रीमती चंद्रमति',muhurthamBtn:'शुभ मुहूर्त →',muhurthamLabel:'॥ शुभ मुहूर्त ॥',weddingHour:'विवाह की शुभ घड़ी',month:'अक्टूबर',hint:'शुभ विवाह समय देखने के लिए नीचे दिए गए बटन को दबाएँ',reveal:'✦ मुहूर्त देखें ✦',timeLabel:'विवाह का समय',time:'रात्रि 07:29',dateLine:'शुभ मुहूर्त • गुरुवार • 29 अक्टूबर 2026',days:'दिन',hours:'घंटे',minutes:'मिनट',seconds:'सेकंड',weekday:'गुरुवार • 2026',venueName:'टाउन हॉल',venueCity:'भीमावरम',venueBtn:'विवाह स्थल →',venueLabel:'॥ विवाह स्थल ॥',welcome:'आपके आगमन की प्रतीक्षा में...',venueSmall:'विवाह स्थल',maps:'📍 Google Maps पर स्थल देखें',venueMsg:'अपना अमूल्य समय हमारे साथ साझा करें<br>और वर-वधू को अपना आशीर्वाद दें।',finalBtn:'अंतिम निमंत्रण →',save:'SAVE THE DATE',finalNames:'श्रीकांत<br><i>♥</i><br>निहारिका',quote:'“दो दिलों के मिलन से शुरू होने वाली यह नई जीवन यात्रा<br>सुख, प्रेम और मंगल आशीर्वादों से भरी रहे...”',blessings:'आपका आशीर्वाद ही हमारा पहला उपहार है',again:'निमंत्रण फिर से देखें ↺',revealDone:'♥ शुभ मंगल मुहूर्त ♥',hintDone:'शुभ विवाह समय आपके सामने है ✨',musicOn:'Music ON',musicOff:'Music OFF'}};
let currentLang='te', revealed=false;
function setLang(lang){currentLang=lang;document.documentElement.lang=lang;document.body.classList.remove('lang-te','lang-en','lang-hi');document.body.classList.add('lang-'+lang);document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));const t=translations[lang];document.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;if(t[k]!==undefined)el.innerHTML=t[k]});document.title=lang==='te'?'సారే వారి పెళ్లిసందడి | శ్రీకాంత్ ♥ నిహారిక':lang==='hi'?'सारे श्रीकांत ♥ बलिवाडा निहारिका | शुभ विवाह':'Sare Srikanth ♥ Balivada Niharika | Wedding Invitation';if(revealed){document.querySelector('#reveal').textContent=t.revealDone;document.querySelector('#hint').textContent=t.hintDone}document.querySelector('#musicLabel').textContent=musicOn?t.musicOn:t.musicOff}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
let timerStarted=false;reveal.onclick=()=>{details.style.maxHeight='520px';details.style.opacity=1;revealed=true;const t=translations[currentLang];document.querySelector('#hint').textContent=t.hintDone;reveal.textContent=t.revealDone;if(!timerStarted){timerStarted=true;const target=new Date('2026-10-29T19:29:00+05:30').getTime();setInterval(()=>{let x=Math.max(0,target-Date.now());d.textContent=String(Math.floor(x/86400000)).padStart(2,'0');h.textContent=String(Math.floor(x/3600000)%24).padStart(2,'0');m.textContent=String(Math.floor(x/60000)%60).padStart(2,'0');s.textContent=String(Math.floor(x/1000)%60).padStart(2,'0')},1000)}};
const petals=document.querySelector('#petals');setInterval(()=>{let p=document.createElement('i');p.className='petal';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*180-90)+'px');p.style.animationDuration=7+Math.random()*7+'s';petals.appendChild(p);setTimeout(()=>p.remove(),15000)},650);
go(1);
const audio=document.getElementById('weddingMusic'),musicBtn=document.getElementById('musicBtn'),musicLabel=document.getElementById('musicLabel');audio.volume=.125;
let musicOn=false;
musicBtn.addEventListener('click',()=>{if(audio.paused){audio.play().then(()=>{musicOn=true;musicBtn.classList.add('on');musicBtn.setAttribute('aria-pressed','true');musicBtn.textContent='❚❚';musicLabel.textContent=translations[currentLang].musicOn}).catch(()=>{})}else{audio.pause();musicOn=false;musicBtn.classList.remove('on');musicBtn.setAttribute('aria-pressed','false');musicBtn.textContent='♫';musicLabel.textContent=translations[currentLang].musicOff}});
setLang('te');
